code smell

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -6,7 +6,14 @@ if [[ "$STAGED_GO_FILES" = "" ]]; then
   exit 0
 fi
 
+GOLANGCI_LINT=$GOPATH/bin/golangci-lint
 GOLINES=$GOPATH/bin/golines
+
+# Check for golangci-lint
+if [[ ! -x "$GOLANGCI_LINT" ]]; then
+  printf "\t\033[41mPlease install golangci-lint (go install github.com/golangci/golangci-lint/cmd/golangci-lint)"
+  exit 1
+fi
 
 # Check for golines
 if [[ ! -x "$GOLINES" ]]; then
@@ -37,3 +44,12 @@ else
  printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
 fi
 
+printf "${LIME_YELLOW}Running golangci-lint on all staged *.go files...${NORMAL}\n"
+golangci-lint run
+
+if [[ $? != 0 ]]; then
+  printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
+  exit 1
+else
+ printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
+fi
